### ISSUE TITLE
In the page titles, special characters aren't rendered properly

### ISSUE THREAD

**Issue by lauradhamilton** [natew/obtvse2#11]
Example: http://natewienert.com/remove-your-alarm-safety-net

Page title: Remove your alarm safety-net &amp; fix your sleep

Should be: Remove your alarm safety-net & fix your sleep

I'm talking about the page title that appears in the browser tab only. HTML in the post itself renders fine.

**Comment by harrisongill** [comment]
Would solving this involve adding .html_safe in either the `app/helpers/page_title_helper.rb` or `application.html.slim`?
