### ISSUE TITLE
How to run in production mode?

### ISSUE THREAD

**Issue by beta4better** [natew/obtvse2#15]
I have to add rails_env development; at nginx server:
server{
    ...
    rails_env development;
    ....
}

without this line, it does not work. 
How to make it work in production mode?

**Comment by shilov** [comment]
You probably just need to set an environment variable like so:

```
$ export RAILS_ENV=production
```

That won't persist if you restart your server but it's impossible to properly answer your question without knowing how you're starting you're booting up the app, i.e. manually via command line or via a process manager of some sort.

**Comment by beta4better** [comment]
@shilov Thank you.

```
RAILS_ENV=production bundle exec rails s
```

It works.

But the icons for twitter, github at the right sidebar misisng.

But if I just run `bundle exec rails s`, there is no problem.

Any suggestion.
Thanks in advanced.

**Comment by shilov** [comment]
In development, the built-in Rails server (webrick) handles all requests including static assets (images, css, etc)
In production, requests for static assets are supposed to be handled by a web server, such as nginx. 

While you have the option to tell Rails to handle static assets in production, it is strongly discouraged.
