### ISSUE TITLE
Can not login the admin panel

### ISSUE THREAD

**Issue by jiangplus** [natew/obtvse2#20]
I have installed the obtvse2 application locally, but when I try to login the admin panel, it redirects to the homepage. Is there any document of how to generate an initial administrator?

**Comment by matt7277** [comment]
Hi jiangplus, did you try going to the /root_directory/user/new ? 

When you actually browse to the the user new route, you should see the user creation dialogue. I know this was a little confusing for me at first as well

**Comment by natew** [comment]
My apologies for this. At one point this was a pretty seamless process and was broken. I did one big round of cleanup on it a month or so ago and this will be my focus the next time I do another round.  For now, what @matt7277 said should work, it may just take a couple tries.

Look for an icon in the top right corner to login to admin once you've gotten logged in.

**Comment by luckypoem** [comment]
hi.
i installed ur app.but what's the default password? and username is the email address specified in info.yml?

**Comment by matt7277** [comment]
Hi luckypoem, did you try going to the /root_directory/user/new ? 

If you rake routes, you should be able to see this route + all other available routes within the config/routes.rb

**Comment by luckypoem** [comment]
hi,matt7277:
i don't understand very much what u said.can u concretely tell me how to create the login id and its password?

**Comment by Gerstep** [comment]
Still impossible to log in

**Comment by natew** [comment]
See my comment on #6
