### ISSUE TITLE
Admin panel not working on demo

### ISSUE THREAD

**Issue by harrisongill** [natew/obtvse2#27]
When going to the demo version and entering the credentials from the documentation, the application does not seem to log in and takes the user back to the home page with zero admin functionality.

**Comment by notslang** [comment]
+1
same for me

**Comment by nateberkopec** [comment]
Yup - some joker probably changed the password. Needs a script to reset it back every few hours.

**Comment by brodock** [comment]
You can change the table permission, to disable updates on the "user table"

**Comment by natew** [comment]
It's been working but the login flow is a little buggy. It redirects back to the home page after logging in rather than going to admin. Theres a new button on the top right though to go to admin.

If someone puts together a pull request to fix that I'll accept.
