### ISSUE TITLE
Switching themes

### ISSUE THREAD

**Issue by myfashionhub** [natew/obtvse2#29]
I don't know if anyone is still maintaining this. This is more of a question. But I'd like to see where the theme is specified so I can switch among themes.

**Comment by dented** [comment]
@myfashionhub you switch the themes inside the theme.css.scss file by importing.

![theme_css_scss_ _obtvse2](https://cloud.githubusercontent.com/assets/2134880/4020039/2f48b07c-2aa0-11e4-9fd5-a15e7b7309e5.jpg)

**Comment by myfashionhub** [comment]
Thanks a lot. Maybe it would be helpful to include this in the README.
