### ISSUE TITLE
When I spin up a new app, I can't create the first user

### ISSUE THREAD

**Issue by lauradhamilton** [natew/obtvse2#6]
I am running obtvse2 locally.

The server is up and running fine.

When I go to http://localhost:3000/admin then I see a form asking for my email address and password. 

However, I never had a chance to set up my username and password. When I run "select \* from users" I get no results.

Looking at the code, it seems like the intent is to have a GUI to create the first user? For some reason, I can't quite get this to work.

Thanks for making obtvse. It's beautiful :-)

UPDATE: I created a user via rails console, and now admin/login is working fine. If that's the expected workflow, I'd be happy to update the README to explain that a little bit. If it's supposed to work via GUI, then maybe there is a bug.

**Comment by BumpyClock** [comment]
I'm new to ruby but I wanted to try out Obtvse.. could you either add that to the readme or reply here.

Thanks :+1:

**Comment by lauradhamilton** [comment]
Sure. Here's what I did:

First start a console session with:
    rails console

Then create a new user:
    u = User.new(:email => "youremailaddress", :password => "yourpassword", :password_confirmation => "yourpassword")
    u.save

Now you have a new user created, and you can login at localhost:3000/admin

**Comment by kristi** [comment]
Looks like there's a modal create user form that loads if you don't have any users yet, but it doesn't pop up for some reason

**Comment by antoniorosado** [comment]
I went to http://localhost:3000/users/new

**Comment by amxn** [comment]
We could have a default user created through a migration as well.

**Comment by natew** [comment]
Modal is broken, just have no time at the moment. In a month or so my schedule will be much more clear.

This should only be a 10-15 minute fix if anyone wants to look at it. The code is all there, just was broken at some point.

**Comment by luckypoem** [comment]
hi.laura:
I still can't create the first user.i follow ur instruction as below,but it seems some error happened.how to 
fix it?

irb(main):004:0> u = User.new
=> #<User id: nil, username: nil, email: nil, crypted_password: nil, salt: nil, created_at: nil, updated_at: nil, remember_me_token: nil, remember_me_token_expires_at: nil, reset_password_token: nil, reset_password_token_expires_at: nil, reset_password_email_sent_at: nil, last_login_at: nil, last_logout_at: nil, last_activity_at: nil, failed_logins_count: 0, lock_expires_at: nil, last_login_from_ip_address: nil>
irb(main):005:0>

**Comment by lauradhamilton** [comment]
Lucky, try going to this url: http://localhost:3000/users/new

That should work provided you don't have any users yet.

I am not sure why creating a user via rails console is not working for you.

**Comment by amxn** [comment]
@lauradhamilton I'd suggest you start using Rails 1.9+ syntax so that you wouldn't need to rewrite it later on. Eg: user = User.new(email: 'youremailaddress', password:  'yourpassword', password_confirmation: 'yourpassword') (Always use descriptive variable names as well.)

Also, try using user.save! (where user is an instance of the User model) and check the exception it throws (ActiveRecord method's bang counterparts throw exceptions on failure.) That should give you a better idea to debug it.

**Comment by luckypoem** [comment]
hi.laura:
tks for ur advice.i succeeded.my site: http://as3.brite.biz:3008/ ,but how to make the ruby app integrate with apache or nginx?i see ur site: http://www.lauradhamilton.com/ has no port no.

**Comment by lauradhamilton** [comment]
Hi Lucky,

You have a couple options. One option is you can use a platform as a service such as Heroku, which will really handle most of the system administration for you. My blog is running on heroku (it's free). That might be a good option.

If you are doing the server setup stuff yourself, say on AWS, then you can use apache/passenger (will need to install a gem), spin up the app running port 8080, and then send http traffic (80) to 8080. That can be configured in linux. You can read tutorials for this on Google -- it's not trivial and it will vary a bit depending on your hosting provider & operating system.

**Comment by lauradhamilton** [comment]
This is a duplicate of #22

**Comment by natew** [comment]
Closed with #22
