### ISSUE TITLE
Login to demo app doesn't seem to do anything

### ISSUE THREAD

**Issue by kristi** [natew/obtvse2#7]
I try to login to the demo app, and I just get redirected to the obtvse2.herokuapp.com page.  I don't see any sort of admin interface.

**Comment by ClaytonHughes** [comment]
So, it looks like if you crush the window width small enough after logging in, there is an error message:

![obtvse-heroku-error](https://f.cloud.github.com/assets/226432/936907/10a64132-00c8-11e3-8f1a-c41226eba349.png)

**Comment by KevinTCoughlin** [comment]
Same error here. Kind of a deal breaker in considering this blog platform.

**Comment by natew** [comment]
Should be fixed.
